// Auto-generated barrel file for features/dashboard/presentation/widgets
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/dashboard/presentation/widgets/app_stat_card.dart';
export 'package:fed_tms/features/dashboard/presentation/widgets/setup_card.dart';
