// Auto-generated barrel file for features/drivers/data/models
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/drivers/data/models/driver.dart';
