// Auto-generated barrel file for features/compliance/presentation/screens
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/compliance/presentation/screens/courses_screen.dart';
export 'package:fed_tms/features/compliance/presentation/screens/training_screen.dart';
