// Auto-generated barrel file for features/drivers/providers
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/drivers/providers/driver_provider.dart';
