// Auto-generated barrel file for features/analytics/presentation/screens
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/analytics/presentation/screens/analytics_screen.dart';
export 'package:fed_tms/features/analytics/presentation/screens/reports_screen.dart';
