// Auto-generated barrel file for features/dashboard/presentation/screens
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/dashboard/presentation/screens/dashboard_screen.dart';
