// Auto-generated barrel file for features/messaging/data/models
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/messaging/data/models/conversation.dart';
export 'package:fed_tms/features/messaging/data/models/message.dart';
