// Auto-generated barrel file for features/company/data/models
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/company/data/models/company.dart';
