// Auto-generated barrel file for features/loads/data/services
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/loads/data/services/load_service.dart';
