// Auto-generated barrel file for features/company/presentation/screens
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/company/presentation/screens/company_screen.dart';
