// Auto-generated barrel file for features/settings/providers
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/settings/providers/user_provider.dart';
