// Auto-generated barrel file for features/drivers/presentation/screens
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/drivers/presentation/screens/driver_details_screen.dart';
export 'package:fed_tms/features/drivers/presentation/screens/drivers_screen.dart';
export 'package:fed_tms/features/drivers/presentation/screens/eld_screen.dart';
export 'package:fed_tms/features/drivers/presentation/screens/hos_screen.dart';
export 'package:fed_tms/features/drivers/presentation/screens/hos_tracking_screen.dart';
