// Auto-generated barrel file for features/messaging/data/services
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/messaging/data/services/message_service.dart';
