// Auto-generated barrel file for features/notifications/presentation/screens
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/notifications/presentation/screens/notifications_screen.dart';
