// Auto-generated barrel file for core/routers
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/core/routers/go_router.dart';
