// Auto-generated barrel file for features/messaging/providers
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/messaging/providers/message_provider.dart';
