// Auto-generated barrel file for features/drivers/presentation/widgets
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/drivers/presentation/widgets/driver_card.dart';
export 'package:fed_tms/features/drivers/presentation/widgets/driver_detail_card.dart';
