// Auto-generated barrel file for features/drivers/data/services
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/drivers/data/services/driver_service.dart';
