// Auto-generated barrel file for features/loads/providers
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/loads/providers/load_provider.dart';
