// Auto-generated barrel file for features/auth/data/models
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/auth/data/models/user.dart';
