// Auto-generated barrel file for features/documents/presentation/screens
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/documents/presentation/screens/documents_manager_screen.dart';
export 'package:fed_tms/features/documents/presentation/screens/documents_screen.dart';
