// Auto-generated barrel file for core/styles
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/core/styles/app_theme.dart';
export 'package:fed_tms/core/styles/typography.dart';
