apiVersion: v1
kind: Namespace
metadata:
  name: {{NAMESPACE}}
  labels:
    name: {{NAMESPACE}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{NAMESPACE}}-config
  namespace: {{NAMESPACE}}
data:
  nginx.conf: |
    user nginx;
    worker_processes {{WORKER_PROCESSES}};
    error_log /var/log/nginx/error.log {{LOG_LEVEL}};
    pid /var/run/nginx.pid;

    events {
        worker_connections {{WORKER_CONNECTIONS}};
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /var/log/nginx/access.log main;

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout {{KEEPALIVE_TIMEOUT}};
        types_hash_max_size 2048;
        client_max_body_size {{CLIENT_MAX_BODY_SIZE}};

        gzip on;
        gzip_disable "msie6";
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types text/plain text/css text/xml text/javascript application/json application/javascript application/xml+rss application/rss+xml font/truetype font/opentype application/vnd.ms-fontobject image/svg+xml;

        include /etc/nginx/conf.d/*.conf;
    }
  
  default.conf: |
    server {
        listen {{HTTP_PORT}};
        server_name {{SERVER_NAME}};

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }

        error_page 404 /404.html;
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{NAMESPACE}}-html
  namespace: {{NAMESPACE}}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>{{PAGE_TITLE}}</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 0;
                display: flex;
                justify-content: center;
                align-items: center;
                min-height: 100vh;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            }
            .container {
                text-align: center;
                background: white;
                padding: 2rem;
                border-radius: 10px;
                box-shadow: 0 10px 25px rgba(0,0,0,0.2);
            }
            h1 {
                color: #333;
                margin: 0 0 1rem 0;
            }
            p {
                color: #666;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>{{PAGE_TITLE}}</h1>
            <p>{{PAGE_MESSAGE}}</p>
        </div>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{NAMESPACE}}
  namespace: {{NAMESPACE}}
  labels:
    app: {{NAMESPACE}}
spec:
  replicas: {{REPLICAS}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{NAMESPACE}}
  template:
    metadata:
      labels:
        app: {{NAMESPACE}}
    spec:
      nodeSelector:
        node-type: {{NODE_TYPE}}
      containers:
      - name: nginx
        image: nginx:{{NGINX_VERSION}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{HTTP_PORT}}
          name: http
          protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: html
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            cpu: {{CPU_REQUEST}}
            memory: {{MEMORY_REQUEST}}
          limits:
            cpu: {{CPU_LIMIT}}
            memory: {{MEMORY_LIMIT}}
        livenessProbe:
          httpGet:
            path: /health
            port: {{HTTP_PORT}}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: {{HTTP_PORT}}
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: nginx-config
        configMap:
          name: {{NAMESPACE}}-config
          items:
          - key: nginx.conf
            path: nginx.conf
          - key: default.conf
            path: default.conf
      - name: html
        configMap:
          name: {{NAMESPACE}}-html
---
apiVersion: v1
kind: Service
metadata:
  name: {{NAMESPACE}}
  namespace: {{NAMESPACE}}
  labels:
    app: {{NAMESPACE}}
spec:
  type: NodePort
  ports:
  - name: http
    port: {{HTTP_PORT}}
    targetPort: {{HTTP_PORT}}
    nodePort: {{HTTP_NODEPORT}}
    protocol: TCP
  selector:
    app: {{NAMESPACE}}