// Auto-generated barrel file for features/company/presentation
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/core/widgets/index.dart';
