// Auto-generated barrel file for features/messaging/presentation/screens
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/messaging/presentation/screens/messages_screen.dart';
export 'package:fed_tms/features/messaging/presentation/screens/messaging_screen.dart';
