// Auto-generated barrel file for features/documents/data/models
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/documents/data/models/document.dart';
