// Auto-generated barrel file for features/auth/data/services
// Generated by Ultimate Flutter Auto-Fixer
// Do not manually edit - changes will be overwritten

export 'package:fed_tms/features/auth/data/services/auth_service.dart';
